package adventofcode2024.day12

import kotlin.test.assertEquals
import org.junit.Test

internal class Day12KtTest {
    private val program = ProgramDay12(
        brutInputs = listOf(
            "RRRRIICCFF",
            "RRRRIICCCF",
            "VVRRRCCFFF",
            "VVRCCCJFFF",
            "VVVVCJJCFE",
            "VVIVCCJJEE",
            "VVIIICJJEE",
            "MIIIIIJJEE",
            "MIIISIJEEE",
            "MMMISSJEEE",
        ).map { it },
        debug = true
    )

    @Test
    fun part1_1() {
        assertEquals(
            expected = "772",
            actual = ProgramDay12(
                brutInputs = listOf(
                    "OOOOO",
                    "OXOXO",
                    "OOOOO",
                    "OXOXO",
                    "OOOOO",
                ).map { it },
                debug = true
            ).part1()
        )
    }

    @Test
    fun part1() {
        assertEquals(
            expected = "1930",
            actual = program.part1()
        )
    }

    @Test
    fun part2_1() {
        assertEquals(
            expected = "436",
            actual = ProgramDay12(
                brutInputs = listOf(
                    "OOOOO",
                    "OXOXO",
                    "OOOOO",
                    "OXOXO",
                    "OOOOO",
                ).map { it },
                debug = true
            ).part2()
        )
    }

    @Test
    fun part2_2() {
        assertEquals(
            expected = "80",
            actual = ProgramDay12(
                brutInputs = listOf(
                    "AAAA",
                    "BBCD",
                    "BBCC",
                    "EEEC",
                ).map { it },
                debug = true
            ).part2()
        )
    }

    @Test
    fun part2_3() {
        assertEquals(
            expected = "236",
            actual = ProgramDay12(
                brutInputs = listOf(
                    "EEEEE",
                    "EXXXX",
                    "EEEEE",
                    "EXXXX",
                    "EEEEE",
                ).map { it },
                debug = true
            ).part2()
        )
    }

    @Test
    fun part2_4() {
        assertEquals(
            expected = "368",
            actual = ProgramDay12(
                brutInputs = listOf(
                    "AAAAAA",
                    "AAABBA",
                    "AAABBA",
                    "ABBAAA",
                    "ABBAAA",
                    "AAAAAA",

                    ).map { it },
                debug = true
            ).part2()
        )
    }

    @Test
    fun part2_5() {
        assertEquals(
            expected = "102",
            actual = ProgramDay12(
                brutInputs = listOf(
                    "AAAC",
                    "ABBA",
                    "AAAA",
                    ).map { it },
                debug = true
            ).part2()
        )
    }

    @Test
    fun part2_6() {
        assertEquals(
            expected = "4",
            actual = ProgramDay12(
                brutInputs = listOf(
                    "A",
                    ).map { it },
                debug = true
            ).part2()
        )
    }

    @Test
    fun part2() {
        assertEquals(
            expected = "1206",
            actual = program.part2()
        )
    }

    @Test
    fun part2_final() {
        assertEquals(
            expected = "923480",
            actual = ProgramDay12(
                brutInputs = listOf(
                    "MMMMMMMMMMMMWWWWWWWWAAAAAAAAAAAAAAAASSSSSSHHHIIHHHHHHHGGGGGGGGGXXXXXXXXEEEEEEENPMMMMMMMMMMPPPPPPPPPPPPPPPAAAHHPHHHHHHHHHHHHTTTTTTTTBBBBWWRRR",
                    "MMMMMMMMMMWWWWWWWWWAAAAAAAAAAAAAAAAASSSSSSHHHHHHHHHHGHGGGGGGGGGXXXXXXEEEEEEEENNNMMMMMMMMMMPPPPPPPPPPPPPPPAAAHHHHHHHHHHHHHHHDTTTTQTBBBBWWWWRR",
                    "MMMMMMMMMMMWWWWWWWWAAAAAAAAAAAAAAAAAASSSHHHHHHHHHHHHGGGGGGGGGGGXXXXXEEEEEENNNNNMMMMMMMMMMFPPPPPPPPPPPPPPPAAAHHHHHHHHHHHHHHHHTTTLTBBBBWWWWWWW",
                    "MMMMMMMMMMMWVWWWWAAAAAAAAAAAAAAAAAAASSSSHHHHHHHHHHTTGGGGGGGGGGXXXXXXEEEEEEENNNNNMMMMMMMMMPPPPPPPPPPPPPPPPPAAHHHHHHHHHHHHHHHHTTTTTBBBBBBWWWWW",
                    "MMMMMMMMMMWWWWWWWWAAAAAAAAAAAAAAAAAAAASSHHHHHHHHHHTHGGGGGGGGGGXXXXEEEEEEEEENNNNNMMMMMMMMMPPPPPPPPPPPPPPPPPRRHHHHHHHHHHHHHHHHTTTTBBBBBWWWWWWW",
                    "MMMMMMMMMWWWWWWWWWAAAAAAAAAAAAAAAAAAAAUSHHHHHHHHHHHHHGGGGGGGGGGXXXXEESEEEENNNNNMMMMMMMMPPPPPPPPPPPPPPPPPPPRRRHDDHHHHHHHHHHHHTTTTTTBBWWWWWWWW",
                    "MMMMMMMMMXWWWWWWWAAAAAAAAAAAAAAAAAAAAESSJHHHHHHHHHHHHGGGGGGGGGGGXXEEESEEEEEENNMMMMMMMMMPPPPPPPPPPPPPPPPGGPRRRRRRRHHHHHHHHHHRRRRTHHHBWWWWWWWW",
                    "MMMMMMMMMWWWWWWWWWAAAAHAAAAAAAAAAQADAAYJJJHHHHHHHHHHGGGGGGGGGGGGGXXXESSSSEEEEEMMMMMMMMMMPPPGPPPYPPPPPPGGRRRRRRRRRHHHHHHHHHHHRRRHHHHBWWWWLWWW",
                    "MWWMMMMWWWWWWWWWWAAAAAAAAAAAAQQAAQQRYYYYJJJHHHHHHHHGGGGGGGGGGGXSSXXXSSSSSSEEEEMMMMMMMMMMMPGGLPEYYPPPPPGGRRRRRRRRFHHHHHHHHHIHHHHHHHHHWDWWWWWW",
                    "MWWWMXXXWWWWWWWAAAAAAAAACAAAAAQQQQQRRYYYJJJHHHHHHHHGGGGGGGGGGGGSSSSSSSSSSSEEEMMMMMMMMMMMPPMLLEEEYPPPPGGGRTRRRRRFFHHHHHHHHHIIHHHHHHHHHDDDWWWW",
                    "WWWWWWWWZZWWWWWIAAAAAAMAMCMMMQQQQQQRYYYYHHHHHHHHHQHGGGQQGGGGQQGSSSSSSSSSSSSEMMMMKKKMMMMMMMMMLEEEEPPPPGGGRRRFFFRFFFFFHFHHHHHIHHHHHHHHHHHHWWWW",
                    "WWWWWWWZZZZWWWWOXAAOAAMMMMMMMQQQRRRRBYVVVVHHAHWHHQQGQQQQQQGGQQSSSSSSSSSSSSSEEMMMKKKKMMMMMMMLLEEEEFIIPGFFFFRFFFFFFFFFFFHHHFHHHHHHHHHHHHHHVWWW",
                    "WWWWWWWWZZZZZZZOXOOOOOMMMMMRMMQQRRRMRVVVVVHEEEHHQQQQQQQQQQQQQQQSSSSSSSSSSSSSEEEKKKKMMMMMMMNNQEEEEFFIPFFFFFFFFFFFFFFHFFFHFFHHHHHHHHHHHKHBWWWW",
                    "WWWWWWWWWZZZZZZOOOOOOOMMMMMMMMRRRLRMRRVVEEEEEEEHQEQQQQQQQQQQSSSSSSSSSSSSSSSSEEEECKKKMMMMMQQQQQQBFFFFFFFFFFFFFFFFFFFHHHHHHHHHHHHHHHHHHKWWWWWW",
                    "WWWWWWWWWZZZZZZZOOONNOMMMMMMMMMRRRRRRRRVEEEEEEEEEEEQQQQQQQQQQSSSSSSSSSSSSZZSEEEEKKKKKMMMKQQQBBBBBFNFFFFFFFFFFFFFFHHHHDDHYHHHHHHHHHHHHKKWWWWW",
                    "WWWWWWWFWWZZZZZZZZONNNMMMMMMMMQRRRRRRRREIEEEEEEEEEEQQPPPPPQQQQSSSSSSSSSSSSZSEEEKKKKKKKKKKQQQQQQBFFFFFFFFFFFFFFFFFHHHXXDXYHBHHHHHHHHHHKKKKWWK",
                    "WMMMMFFFFFFZFZZNZZNNNNMMMMFFMQQFRRRRRREEEEEEEEEEREEPQPPPPPQQQQBSSCSSSSSSSZZSSKKKKKKKKKKKKKQQQQQQMFFFFFFFFFFFFFHHHHHHXXXXXHBHHHHHHHHHHHKKKKKK",
                    "CMMMAFFFFFFFFFNNZNNNNNNNMMMFFFQFRRRRRRRRREEEETTTTRPPPPPPPPPQQQQQQSSSSSSSSZZZKKKKKKKKKKKKKQQQQQQQMFFFFFFFFFFFFFHHHHHXXXXXXXBHHHHHHUHHKKKKKKKK",
                    "CCMMMMFFFFFXXXXNNNNNNNMMMMFFFFFFFRRRRRSSEEEEETTTTSSPPPPPPPPQQQQRRRRRRSSZZZZZZKKKKKKKKQQQKQQQKQQQQQFFFFFFFMFFFFHHHHHXXXXXXXHHUHHHHUHHKKKKKKKK",
                    "MMMMMMMMXFFXXXXNNNNNNNNMFFFFFFFUUUURRRRSSSSESTTTTSSSPPPPPPPQQQQQRRRRRRZZZZZZZKKKKKKKKQQQQQQQQQQQQYFFFFFFMMFFFFHHHHHHXXXHHHUUUHUUHUHHKKKKKKKK",
                    "MMMSMMMMXXXXXXNNNNXNNNNLFFFFFFFFFFFERRVSSSSSSTTTTSSDJPPPPPPQQQQRRRRRZZZZZZZZZKKKKKKMMMMQQQQQQQQYYYYFFFFFMMMFFFHHHHHHHHXHHUUUUUUUUUUHHKKKKKKK",
                    "WMMSMMMMMMXXXXXXXXXXXFCFMFFFFFFFFFFELVTTTTTTTTTTTTTTTTPPPPPQQQQRRRRRRZZZZZZZSKKKKKKMQMMQQQQQQQQQQYYFFFFFFFMMMMHHHHHHHHHHUUUUUUUUUKUKKKKKKKKK",
                    "NMOMMMMMMXXXXXXXXXXXXFFFFFFFFFFFFFFLLLTTTTTTTTTTTTTTTTPPPPNQQQQRRRRRRZZZZZZGSKSSKVVSQQMQQQQQQQQQYYYYYFFFFFFMMHHHHHHHHHHHUUUUUUUUUKKKKKKKKKKK",
                    "NNMMMMMMMXXXXXXXXXXXFFXFFFFFFFFFFFFLLLTTTTTTTTTTTTTTTTZPPPNZZRRRRRRRRRRZZZSGSSSSSSSSBQQQQQQQQQQQQYYYYYFFFFFMMMHHHHHHHHHHHUUUUUUUUKKKKKKKKKKK",
                    "NNNNMMMMMNXXXXXXXXXXXXXFFFFFFFFFFFFFFLTTTTTTTTTTTTTTTTZPPPNZZZZZZRRVVVVZZSSSSSSSSSSSSQQQQQQQQQQQQQCYCYYFFFFMMMHHHHHHHHHHHUUUUUUUUUUKKKKKKKKK",
                    "NNNNMMNMMNNXXXXXXXXXXXXFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTPPPPZZZZZZVVVVVVVVVVSSSSSSSSSSSSQQQQQQQQQQQCCCCYYYBBBMMMMMHHHHHHHHUUUUUUUUUUUKKKKKKKKK",
                    "NNNNMRNNNNNNXXXXXXXXXFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTTTZZZZZZZZZUUUVVVVVVVVSSSSSSSSSSSSQQQQQQQQQHHCCGGBYBKBBMMMMMMMHHHHHHHUUUUUUUUKKKKKKKKKKK",
                    "NNNNNNNNNNNNXXXXXXXXXXFFQFFFFFFFFGFFTTTTTTTTTTTTTTTTTTZZZZZZZZUUUUUVVVVVVSSSSSSSSSSSSSPQQQQYYYQHHCCCGBYBBBBBBMMMMMMHHHHRREUUUUUUUUEEOOKKOOKK",
                    "NNNKKNNNNNNXXXXXXXXXXXXXXSFHFYFFFFQOTTTTTTTTTTTTTTTTTTZZZZZZZZUUUUVVVVMVVSSSSSSSSSSUSUPQQQYYMMMMHCCCWBBBBBBBBMMMMMMMHHHHEEEEEUUUUUEEEOKOOOKK",
                    "NNVKKNNNNNXXXXLXLLXXXXXXXXXHHYFFXQQQTTTTTTTTTTTTZZZZZZZZZZZZZZVVVVVVVVMMVSSSSSSSSSSUUUUBUUYYYMMMMCCWWWWBBWRRRMMMMMMEHHHHHHEEEUEUEEEEEOOOOOKO",
                    "NJVVKKNNNXXXXLLLLLLXXXXXXHHHHYYFXQQQTTTTTTTTTTGZZZZZZZZZZZZZZZQQVVVVVVMMMSSSSSSSSSSUUUUUUUUUMMMWWWWWWWWBBWRRRRRRMMMEEHHEHEEEEEEEEEEEEEEHOOOO",
                    "QJVVKKKNNXXXXLLLYYYYYYYXXXHYYYYYXQXQTTTTTTTTTTGZZZZZZZZZZZZZQQQVVVVVVVMMMMSMSSSSSFSCUUUUUUKMMMMWWWWWWWWWBWWRRRRRMMEEEHEEEEEEEEEEEEEEEEHHHOHO",
                    "QQVVKKKKNLLLLLLLLYYYYYYYYXHYYYYXXXXXQQBBBBQQBBBBBZZZZZZZZZQZQQQQVVVVVVVMMMMMSSFFFFSCSUUUUUUMMWWWWWWWWWWWWWRRRRRRMRLEEEEEEEEEEEEEEEEEEEHHHHHO",
                    "QQQQQKKKLLLLLLLLLLYYYYYYYXHYZYYYXXXQQQBBBBBBBBBBBNZZZZZZZFQQQVVVVVVVMMVMMMMMMFFFFFSSSUUUUUUUMWWWWWWWWWWRWWRRRRRRRRRZEEEEEEEEEEEEEEEEHEHHHHHO",
                    "QQQQLLLLLLLLLLLLLYYYYYYYYYHYYYYYXXXXXXXBBBBBBBBBBZZZZZZZZQQQQQVVVVVVVMMMMFFFFFFFFFSMUUUUUUPPWWWWWWWWWWWWRRRRRRRRRRRZEEEEEEEEEEEEEEEEHHHHHHHH",
                    "QQDDQQLLLLLLLLLLLYYYYYYYYYHYYYYYYXXXXXXBBBBBBBBBBBZZZZZZZQQQQQVVVQVVVMMMMFXFFFFFFFFFUUUUUUUPPWWWWWWWWWWRZRRRRRRRRRRREEEEEEEEEEEEEEEEHHHHHHHH",
                    "QQQQQQLLLLLLLLLLLLYYYYYYYYYYYYYYYYYXXXBBBBBBBBBBBBQQQZQQQQQQQVVZDDDMMMDMMMFFFFFFFFUUUUUUUUUUPPWWWWWWWWWRRRRRRRRRRRRCCEEEEEEEEEEEEEEEHHHHHHHH",
                    "QQQQQQQLLLLLLLLLLLLYYYYYYYYYYYYYYYYYBBJBBJBBBBBBBBQQQQQQQQQQQZZZDDDDDDDDFFFFFFFFFFUUUUUUUUUUPPWWWWWWWWWRRRRRRRRRRRCCCCCEEEEEEEEEEEEEHHHHHHHH",
                    "QQQQQQQQLLLLLLLLLLLLYYYYYYYYYYYYYYYYBBJJJJJBBBBBBBBQQQQQQQQQMMMMDDDDDDDDDFFFFFFFFFUUUUUUUUUPPPWWWWWWWWWWWRRRRRRRRRRCLLLLLEEEEEEEEEHHHHHHHHHH",
                    "QQQQQQQQLLLLLLLLLLLLLYYYYYYYYYYYYYRRDBBJJJJBBBBBBBBBQQQQQQQMMMMMMAADDDDDFFFFFFFFFUUUUUUUUNNNNNNNNNNWOWWWWRRRRRRRCCCCLLLLLLEEEEEEEEEHHHHHHHHH",
                    "QQQQQQQQLLLLLLLLLLLLLYYYYHYRRRYRYYRRDBBJJJJBBBBBBBBBQQQQQQQMMAAAAAADDDDDFFFFFFFFFFUUUUUUUNNNNNNNNNNWOWWWWRRRRRRJJJJJJLLLLLEEELEEEEHHHHHHHHHH",
                    "QQQQQQQQLLLLLLLLLLLLYYRRIRRRRRRRRYRRDBBJJJJBBBBBBBBBQQQQQQQQMAAAAAADDDDDFFFFFFFFFUUUUUFPPNNNNNNNNNNYWWWWWWJJJJJJJJJJJLLLLLELLLLEEEXHHHHHHHHH",
                    "QQQQQQQKKKLLLLLLLLCRYYRIIRRRRRRRRRRRRBBBJJBBBBBBZBBQQQQQQQTTXTTAIIIIYDDFFFFFFFFFCUCUUFFPPNNNNNNNNNNYWWWWYYJJJJJJJJJJJLLLLLLLLLLLLLHHHHHHHHHH",
                    "OQQQQKQKKKKKLLLLLLCRRRRRRRRRRRRRRRRRRBBBBBBBBBBBSRQQQQQQQQTTTTTTTIIIIIIFFFFFFFCFCCCCCFFFPNNNNNNNNNNYYYYYYYJJJJJJJJJJJTLIILLLLLLLLLLHHHHHHHHH",
                    "OQQQKKKKKKKKKLBBBRRRRRRRRRRRRRRRRRRRRBBBBBBBBSSSSRSQQQQQQQQQTTTTTTRRRRQQFFFFFFCCCCBBBFFFFNNNNNNNNNNYYYYYYYJJJJJJJJJJJTTIILLLLLLLLLLLHHHHHHHH",
                    "OOKKKKKKKKKKKXXRRRRRRRRRRRRRRRRRRRBRRRBBBBSSBSSSSSSQQQQQQQQQTTTTTTRRRRQFFFCFCCCCBBBBBFFPPNNNNNNNNNNYYYYTTYJJJJJJJJJJJTTTIILLLLLLLLLLHHHHHHHH",
                    "OOKKKKKKKKKKKXXXVRRRRRRXRRRRRRRRRBBBBBBBBSSSSSSSSSSQQQQQQQATTTTTTTRRRRRFFCCCCCCBBBBBBBBPPNNNNNNNNNNYYYYYTTJJJJJJJJJJJTTIIIIIILLLLLLLLHHHHHHH",
                    "OKKKKKKKKKKKKXXVVRRRRRRXXRRRRRRRBBBBBBBBBBSSSSSSSSSSQQQQTTTTTTTTTTRRRRRFRCCCCCCBBBBBBBBBBNNNNNNNNNNYYYYYYTJJJJJJJJJJJTIIIIIIILLLLLLLLHHHHHHH",
                    "OKKKKKKKKKKKKKKRRRRRRRRRXXXRRTRRBBBBBBBBBBSSSSSSSSSVQQQQQRTTTTKRRRRRRRRRRRRCCCCBBBBBBBBBBBBRYZZZYYYYYYHYYNTTJJJJJJJJJTIIIIIIILLLLLLLLLLHHHHH",
                    "OOLKKKKKKKKKKKKRRRRRRRRTRRRRRRRBBBBBBBBBSSSSSSSSSSSSQQQQRRRWWTKRRRRRRRRRRRCCCCCBBBBBBBBBBDZRYZZZYYYYYYHHYYTTJJJJJJJJJTTIIIITTLLLLLLLLLLKHHHH",
                    "LLLLKKKKKKKKKKKRRRRRRRRRRBBBBBBBBBBBBBBBSSSSSSSSSSNNNNNRRRRWWKKRRRRRRRRRRRCCCCBBBBBBBBBBBBZZYZZZZZYYYYHHHHHTJJJJJJJJJTTSIIITLLLLLLLLLLKKKHKK",
                    "CLLLLKKKKKKKKKKRRRRRRRRRRMBBBWBBBBBDDBBSSSSSSSSSSSNNNNNWWWWWWWWWRRRCCRRRRRRRCCCBBBBBBBBBBBBZZZZZZYYHHYHHHHHTTTTTXTTTTTTSSDSSLLLGGLLLLLLLKKKK",
                    "LLLBKKKKKKKKOKKRRRRRRRBRRBBBBBBBBBBTDDDQSSSSSSSSSSNNNNNWWWWWGGWWWRCCCCCRRRRRCCBBBBBBBBBSBBBZZZZZZZYYHHHHHHXXTTTXXXXXXXSSSSSSSLLGLLLLLLLKKKKK",
                    "LLLLLKKKKKKKOOOORRRRRRVVVVVBBBBBBBBDDQDQQQSSSSSSSSSSVWWJJWWWWWWWWCCCCCCCRRRRRCBBBBBBBBBBBBBZZZZZZZZYYHHHXXXXXXXXXXXXXXXSSSSSSSLGGLXXXXLJJJJJ",
                    "LLLLLWWWWKWKWWOOOOORROVVVVVVBBBBBBDDDQQQQQSNSSSSSSSVVVWWJWWWWWWWWCCCCCCRRTRRRCBPBBZBPPBBBBBZZZZZZZZDPPPHXLXXXXXXXXXXXXSSSSSSSGGGGOXXXJJJJJJJ",
                    "LLLLLLWWWWWWWOOOOOOOOOVVVVVVVBBBBBBDDDDQQQQSSSSSSSSSSVWWWWWWWWWWWCCCCCCCCRRRCCCPPBBBPPPPXXXXXZZZZZZDPPPPPPXXXXXXXXXVXXXVSSSSGGGGOOXJJJJJJJJJ",
                    "LLLLLLLLOWWWWOOOOOOOOOOOVVVVVBDBBBBBBQQQQQQSSSSSSSSSVVWWWWWWWWWWWCWCCCCCCRRRCCCPPPPPPPKXXXXXZZZZZZZPPPPPPPXXXXXXXXXVVVVVVGGGGGGOOOOJJJJJJJJJ",
                    "LLLLLLLLOOOOOOOOOOOOOOOOVVVVBBBBBBBBQQQQQQQQSSSSSSSSSWWWWWWWWWWCCCWWCWWCCCEECPPPPPPPPPXOOXXXYBZZAAPPPPPPPPPXXCCVVXXVVVVVVVGGGOOOOOOOOOJJJJJJ",
                    "LLLLLELLKOOOOOOOOOOOOOOVVVVVVVVBBBBBQQQQQQQSSSQSQSSSVVWWWWWWWWWWWCWWWWWWWWEECCCCPCPPPPXXXXXXBBZZZHHHPPPPPPPPPPPVVXVVVVVVGVGGGOOOOOOOOOJJJJJJ",
                    "LLLLEEKKKKKKOOOOOOOOOOOVVVVVVVVBBBBBQQQQQQQQSSQQQQQSVVVWWWWWWWWWWWWWWWWWWWEECCCCCCHHPXXXXXXXBBBBZHHHHPPPPPPPPPPVVVVVVVVVVVGGGOOOOOOOOOOOIIII",
                    "LLLLLLKKKKKKOOOOOOOOOOVVVVVVVVVVBBKKVQQQQQQQQSQQQQQSVVVWWWWWWWWWWWWWWWWWWWEEEEHHHHHHHQXXXXXXBBBBWBBHHPPPPPPPPPPVVVVVVVVVVVGGGGOOOOOOOOMOOIII",
                    "LLLLKKKKKKKKKKOOOOOOOOOVVVVVVVVVBVVVVVQQQQQQQQQQQQQSVVVWWWWWWWWUWWWWWWFWWWEEEHHHHHHQQQQXXWXXXBBBBBHHHPHPPPPPPPPVVVVVVVVVVVGGGGOOOOOOOOOOOOII",
                    "HHHHKKKKKKKKKKKOOOOOOVVVVVVVVVVVVVVVVVVQQQQQQQQQQGVVVVVVWWXXXWWHWWWWWWWWWWEEHHHHHHHQQQQQWWXXXBBBBBHHHHHHHPPPPPUVVVVVVVVVVVGGGGOOOOOOOOOOOIIM",
                    "HHHHKKKKKKKKKKOOOOOOVVVVVVVRRRVVRRRVVVVQQQQQQQQQVVVVVVVVVVXXXHHHWWWWWWWWWWWHHHHHHHHQQQWQWWXXXBBBBBHHHHHHHPPPPVVVVVVVVVVVVVGGJJJOOOOOOOOOMMMM",
                    "HHHHKKKKKKKKKKKKKOOOVVVRRRRRRRRRRRRRRVQQQQQQQQQQQMMVVVVVVVVXXHHHHWWWWWWWWWHHHHHHHHHHWWWWWWWXBBBBBHHHHHHHHHHPQQQVVVVVVVVVFFJJJJJOOOOOOOOMMMMM",
                    "HHHHKKKKKKKKKKKKKOOKKVRRRAARRRRRRRRRGVMQQQQSSQQQMMSFVVVVVVXXXXWWWWWWWWWWWWWHHHHHHHUWRWWWWWWXBBBBBHHHHHHHRHHHHQQQQQVVVVFFFFFJJJJBJJJOYOOMMMMM",
                    "HHHHKKKKKKKKKKKKKKZKVVRRRRRRRRRRRRRFVVOOQQQSSQQQMMSSVVVVVVXWWWWWWWWWWZZZZZVHHHHHHUUWWWWWWWPXBBBBCHHHHHHHRHHHRQQKKKVVVVVVVJJJJJJJJJJYYYMMMMMM",
                    "HHHKKKKKKKKKKKKKHKKKKKRRRRRRRRRRRRRFFFFOOQSSSSMMMSSSVVVVVXXXWWWWWWWWWZZZZZZHHHHHHUUWWWWWWWWWWWBCCHHHHHHRRRHHRQQQKKVVKVDVUUNNNJJJJJJJYMMMMMMM",
                    "HHHZKKKKKKKKKKKKKKKKKTRRRRRRRRRRRRRFFFOOOOSSSSSSSSSSSSXVXXXXXWWWWWWWWZZZZZZHHHHHUUUUWWWWWWWWWWWCCCHHHHRRRRRRRQQKKKKKKKKNNNNNNJJJJJJYYMMMMMMM",
                    "ZZHZKAKKZKKKKKKKKKKKKTRRRRRRRRRRRFFFFFOOOOSSSSSSSSSSSSXXXXXXWWWWWWWWZZZZZJZHHHHHUWUWWWWWWWWWWWWCCCHHRRRRRRRRRQKKKKKKKKNNNNNNNJJJYYYYMMMMMMMM",
                    "ZZHZZZZZZBKKKKKKKKKKKKRRRRRRRRRRRFFFFOOOOOSSSSSSSSSSSSSXXXXXXXWWWWWWZZZZZZZZHHHHUWWWWWWWWWWWWWSCCHCHRRRRRRRHRKKWKKKKKNNNNNNNNNNJJYYYMMMMMMMM",
                    "ZZZZZZZZZZZZKKKKKKKKKKRRRRRRRRRRRFFFOOOOOOBSSSSSSSSSSSXXXXXXXXXZWWWWZZZZZZZZZHHUUWWWWWWWWWWWWJSCCHCRRRVRRRRHRLKKKKKKNNNNNNNNNNYYNYYMMMMMMMMM",
                    "ZZZZZZZZZZZZKKKKKKKKKRRRRRRRRRRFRRRFFOOOOOBSSSSSSSSSSXXXXXXXXXXZZZZZZZZZZZZUUUUUUWWEWWWWWWSSSSSCCCCRRRRRRRHHKKKKKKKKNNNNNNNNNNNNNYMMMMMMMMMM",
                    "ZZZZZZZZZZZKKKKKKKKKKRRRRRRRRFFFFFRFOOOOOBBBBSSSSSSSSSXXXXXXXXXZZZZZZZZZZZZUUUUUUWWWBWSWWSSSSSRCCCCRCCRRHHHHKKKKKHKHNNNNNNNNNNYYYYYMMMMMMMMM",
                    "ZZZZZZZZZZZXXKKKKKKKKGGGGRRRFFFFFFFFFFOBBBBBBBNNSSSSSSXXXXXXXXXXWZCZZZZZZZZUUUUUUWWBBWSSSSSSSSSCCCCCCCCCCCCHHKKKKHHHNNNNNNNNNNNYYYYMYYMMMMMM",
                    "ZZZZZZZZZZZWWWWKKKKKKGGGGRRRFFFFFFBBBBBBBBBBBBBBSSSSSSSXXXXXXXXXWCCZZZZZZZUUUUUUUUUUBBSSSSSSSSSCSCCCCCCCCCCCCHHHHHHHHNOOONNNNNYYYYYYYYMMMMMM",
                    "ZZZZZZZZZZZWWWWKKKKKKGGGWFFRFFFFFFBBBBBBBBBBBZBBSSSSSXXXXXXXXXWWWCCZZZZZZZUUUUUUUUUUUBSSSSSSSSSSSSCCCCCCCCCCCHHHHHHHHHSONNNTNNYYYYYYYYMRMMMM",
                    "ZZZZZZZZZZWWWWWKKWKKKKWWWFFFFFFFFFFBBBBBBBBBZZZZZZSSSXXXXXXXXXWWWCCCZZZZZZZUUUUUUUUUUBSSSSSSSSSSSSSCCCCCCCCCUCHHHHHHHHSOTNNTTTTYYYHHHMMMMMMM",
                    "ZZZZZZZZZZWWWWWWWWKWWWWWWWFFFFFFFFFBBWBBBBBBZZZZZXXSSXXXXXXXXWWWWWCCZZZZZZZZZZUUUUUBBBSSSSSSSSSSSSCCCCACCCCCCCHHHHHSSSSSTTTTTTTHHHHHHHHHMMMM",
                    "ZZZZZXXXXXVWWWWWWWWWWWWFFFFFFFFFFFFBXBBBBBBBBBZZZXXSSXXXXXKKWWWWWWCCCZZZZZZZZZZUUUUUBBBSSSSSSSSSCCCCCAAACCCCCHHHHHSSSSSSTTTTTTBHHHHHHHHHMSSM",
                    "ZZXXXXXXXXXXWWWWWWWWWWWWFFFFFFFFFFFFXXXBBBZBBZZZZXXXXXXXXXKKKWWBWWWWZZZZZZZZZZKUUUUUBBBSSSSSSSSSCCCAAAACCCCCHHHHHHSSSSSTTTTTTTTTHHHHHHHHHSSS",
                    "ZXXOXXXXXXXXCWWWWWWWWWWWWFFFFFFFFFFFFXXBEZZZZZZZZZXXXXXXXXXKXXXBBWWBBBZBBZZZBBUUUUUUYBBSSSSSSSSSCCAAAAAQCCCCCAAASSSSSSSTTTTTTTTHHHHHHHHHHSSS",
                    "ZZXXXXXXXXXGXWWWWWWWWWWWWRFFFFFFFFFEXXEEEZEZZZZZZZXXXXXXXZXXXXXXBBBBBBBBBZZZBBBBBUUUYYYYSSSSSSSSSSQAAAAQQQQQQAAAASSASASTTQQTTTHHHHHHHHHSSSSS",
                    "ZZZXXXXXXXXXXWWWWWWWWWWWWWFFFFFFEEEEXXEEEEEEZZZZZXXVXXXXXXXXXXXXXBBBBBBBBZBBBBBBBBBUUWWYYYYYSSSSSSQQQAQQQQQQAAAAAAAAAAATTTTTTTHHHHHHHHHSSSSS",
                    "ZZZXXXXXXXXXXWWWWWWWWWWWWWIFFFFFFEEEXEEEEEEEZZZZXXXXZXXXXXXXXXXXXXBBBBBBBBBWBBBBBWWUWWYYYYYSSSSSQQQQQQQQQQQAAAAAAAAAAAYYYYTTTTHHHHHHHHHSSSSS",
                    "ZZXXXXXXXXXBXWWWWWWWWWWWWIIFFFFEEEEEEEEEEEEEEEZZZXXZZXXXXXXXXXXXBBBBBVBBBBBWWWWWWWWWWWWWYYYYSSSSSQQQQQQQQQQAAAAAAAAAAAYYYYTTTTTTHHUUHHHHSSSS",
                    "ZZZXXXXXXXXXXWWKWWKKEWWWWIIIIUFEEEEEEEEEEEEEEEEZZZXZZXZXXZXXXXXXXBBBVVBVBBWWWWWWWWWWWWWWYYYYSSSSSQQQXQXXQQQQQAAAAAAAAAYYGYTTTTTUUHUUUUUHSSSS",
                    "ZXXXXXXXXXXXXWWKKKKEKIWIIIIIIICCEEEEEEEEEEEEEEEZZZZZZZZZZZXXXXNNXBVVVVVVBBBWWWWWWWWWWWWYYYYYYSSQSQQQXXXXXXXQAAAAAAAAAAAAGGGTTTUUUUUUUUUHSSSS",
                    "ZZZZXYXXXXXXKWKKKKKKKIWUUUUIIICCCCEEEEEEEEEEEEZZZZZZZZZZZXXXXXNNTVVVVVVVVVBWWWWWWWWWWWWYYYYYYSSQQQQQQQQXXXXXAAAAAAAAAARAWWGGGTUUUUUUUUUUUSSS",
                    "ZZZXXXXXXXXXKKKKKKKKKKWUUUUUCCCCCCEEEEEEEEEEEEZUZUZZZZZZZZXXNNNNNVVVVVVVVVVUWWWWWWWWWWWYYYYYQQQQQQQQQXXXXXXCTAAAAAAAAAAAOWGGUUUUUUUUUUUUUUSS",
                    "ZZZZVVXXXXXXKKKKKKKKKKUUUUUUCCCCCCEEEEEEEEEEEEEUUUZZZZZZZZZNNNNNVVVVVVVVVVVVWWWWWWWWWYYYYQYYQQQQQQQQQQXXXXTTTTTAAAAAOOAOOGGUUUUUUUUUUUUUUUSS",
                    "ZZZVVVXXXVVWKKKKKKKKKKVUUUUUNCCCCCCEEBEEEEEUUUUUUUZZZZZZZZZZNNNNVVVVVVVVVVVWWWWWWWWWNQYYQQQQQQQQQQQQQQXXRXTTTTTAAAAAOOOOZGGUUUUUUUUUUUUUUSSS",
                    "ZZVVVVVVVVVVVVKKKKKKKUUUUUCCCCCCCCCCEEEEEEEUUUUUUUZZZZZZZZZZNNNNVLVVVVVVVVVVWWWWNNNNNQYQQQQQQQQQQQQQQQQQQTTTTAAAAAAAAOOJZZZUUUUUUUUUUUUUUSSS",
                    "ZZVVVVVVVVVVVVVKKUKUUUUUUUCCCCCCCCCCCCESSSEEUUUUUUZZZZZZZZZZNNNNVNVVVVVVVVVVWWWQQQQQQQQQQQQQQQQQQQQQQQQQQQQTVAAAAAAAAAOOZZZUXUUUUUUUUUUUUUSS",
                    "ZZVVVVVVVVVVVVVGKUUUUUUUUUUCCPCCCCCCCCCCSSEQUUUUUUZZZZZZZZNNNNNNNNVVVVVVVVVVZWWDQQQQQQQQQQQQQQQQQQQQQQQQQQQQAAAAAAAXXAAOXZZUUUUUUUUUUUCUSSSS",
                    "ZVVVVVVVVVVVVVVKKUUUUUUUUCCCCCCCCCCCCCCSSSVUUUUUZZZZZZZZZZZNNNNNDDDDVVVVVVVZZZWWXXXXXXQQQQAAQQQQQQQQQQQQQDDDAXXAAAAXXXXXXZZZZUZZUUZZZICIIIIS",
                    "ZVVVVVVVVVVVVVVUUUUUUUUUUUUCCCCCCCCCCHHVVVVUUUUUUZZZZZMMZZZNNNNNNDDDVVVVVVVCCCXXXXXXXXQQQAAALQQQQQQQQQQQQQQQXXXXXXAXXXXXXZZZZUUZUUZZIIIIIIII",
                    "ZVVVVVVVVVVVYYYUUUUUUUUUUUECAACCHCCCCHVVVVVUUUUUUZZZZZZMMZBNNNNNNNBDVVVVVCCCCCXXXCXXXXXXXLAALGGGQQQQQQQQQQQOQXXXXXXXXXXXZZZZZUUZZZZIIIIIIIII",
                    "ZVVVRRVVVVVVYJUUUUUUUUUEEEEEACCCCCCCCCVVVVVVUUUUUZZMZZMMMEMNNNNNKKBBVVVTCCCCCCXCCCCXXXXLLLLLLLLLQQQQQQQQQQQQQQXXXXXXXXXZZZZZZUZZZZZIIIIIIIII",
                    "IIIRRRRVVVVVJJJUUUUUYYYYYEEEECGGGGGGGGVVVVVVVVUHHHHMMMMMMMMNNNNNKBBBBBTTTCCCCCCCCCCXXCXLLLLLLLLLLQQQQQQQQQQQQQXXXXXXXXXZZRRZZZZZZZIIZIIIIIII",
                    "IIIIRRRRJVVVTTJUTTYYYYYYYEEEEEGGGGGGGGVVVVVVVVUHHHHHMMMMMMMMNNKKKBBBBBTTTTTCCCCCCCCCCCCCLLLLLLLLLLLLQQQQQQQQQQXXXXXXXXXXXRTRRRRZZZZZZIIIIIII",
                    "IRRRRRRJJVVVTTTTTTYYYYYYYYYEEGGGGGGGGGGVVVVVVVVHWHHHMMMMMMMMMMKKKBBBBGTTTCCCCCCCCCCCCCCCNNNLLLLLLLLLQQQQQQQQSQXXXXXXXTXXRRTRRRRZZOOOIIIIIIII",
                    "RRRRRRRRRDVTTTTTRTYYYYYYYYEEEGGGGGGGGGGVVVVVVWWWWWTTTMMMMMMMMMMKKBBBHGGGTCCCCCCCCCCCCCNNNNLLLLLLLLLLQQQQQQQQQQQXXXXXXTXRRRRRRRRRZOOOOOOIIIII",
                    "RRRRRRRIRDRRRRRTRRRGGEEEYEEEEGGGGGGGGGGVVVVVVWWWWWTTTMMMMMMMMMMKQQBBGGGGCCCCCCCCCCCCKNNNNNLLLLLLLLLPQVVVQQQQQHQXXXTXXTTZZRRRRRRRROOOOOOIIIII",
                    "RRRRRRRIRRRRRRRRRRRGNEEEEEEEEGGGGGGGGGGVVVVVWWWWWSTTTMMMMMMQMMQQQQQGGGGUCCCCCCCCCCCKKNNKLLLLLLLLLLLLQVVVVQYDTDDTTTTTXTTZTRRRRRRRRROOOOOOOIII",
                    "RRRRRRPRRRRRRRRRRRRGNEEEEEEEEGGGGGGGGGGVVVVVVWWWWWTTTMMMMMQQQQQQQQQZGGGGGCCCCCCCCCKKKKKKKKKKLLLLLLLVVVRVDDDDDDDTTTTTTTTTTEEERRRRROOOOOOOOOIN",
                    "RRRRRRPRRRRRRRRRRRRNNNNNNEEEEGGGGGGGGGGVVVVVVWWOZZTTTTTTTTTTTTQQQQVGGGGGGGGCCCCCCCKKKKKKKKKRLLLLLLLVRRRVVDDDDDDTTTTTTTTKKRRRRRRROOOOOOOOOIII",
                    "RRRRRRRRRRRRRRRRRRIINNNNNNNNEGGGGGGGGGGVVVVVVWUOOOTTTTTTTTTTTTQQQQGGGGGGGGYYYYCCCCKIKKKAKVKLLLLLLLDRRRRVVDDDDDDTTTTTTTTTKRRRRRROOOOOOOOOOOOI",
                    "RRRRRRRRRRRRRRRRRRRRNNNNNNMMMMMMMMMMMMMVVVVVVVHOOOTTTTTTTTTTTTQQQQGGGGGGGGGYYYCCCIIIIKAAVVKLLLVLFRRRRRRVREEDDDDTTTTTTTTTRRRRRRRROOOOOOOOOOOO",
                    "RRRRRRRRRRRRRRRRRRRRRNNNNNMMMMMMMMMMMMMHVVVHHHHOOOTTTTTTTTTTTTQQQQGGGGGGGGGGLLCCCIIIIIVVVVVVCVVRRRRRRRRRREEDDDDDTTTTTTTRRRRRDDRROOOOOOOOOOOO",
                    "RRRRRRRRRRRRRRRRRRBRNNNNNNMMMMMMMMMHHHHHHVVHHHHOOTTTTTTTWWWWWWWWWWGGGGGGGGGOLLLLLIIIIVVVVVVVCVVRRRRRRRRRRREDDDDDTTTRRTTTRRRRDHHOOOOOOOOOOOOO",
                    "RRRRRRRRRRRRRRRIRRHHNNNNNNMMMMMMMMMHHHHHHHVHOOOOOTTTTTQTWWWWWWWWWWGGGGGGGGGGGLLLLIIIIIVVVVVVVVVRRRRRRRRRRRROYDDDRTTRRRRRRRRDDDDOOOOOOOOOOOOO",
                    "RRRRRRRRRRRRRRRRRHHHHNNNNNMMMMMMMMMHHHHHHHHHHHHHGTTTTTOTWWWWWWWWWWWWWWGGGGGLLLLLLLLLIIVVVVVVVVVRRRRRRRRRRRROYYRRRRRRRRRRRRRDDDDDDOOOOOEOOOOO",
                    "RRRRRRRRRRERRRRRMSHHHHNNNNMMMMMMMMMMMHHHHHHHHHHHGTTTTTOTWWWWWWWWWWWWWWGGGGGLLLLLLLIIIIIIVVVVVVVRRRRRRRRRRROOOYRRRRRRRRRRRRRDWDDDDODOOOEOOOOO",
                    "RRRRRRRRERERRMMMMSSHHHHNNHMMMMMMMMMMMHHHHHHHGGGGGTTTTTOTWWWWWWWWWWWWWWGGGGLLLLLLLLIIIIIIVVVVVVVRRRRRRRRRRROOORRRRRRRRRRRRRRDDDDDDODDDDDDOOOO",
                    "RRNRRLEEEEEEEMMMSSSSSHHHHHMMMMMMMMMMMHHHHHHHHGGGGTTTTTOTWWWWWWWWWWWWWWGGUGLLLLLLLLLIIIIOOVVVVVVRRRRRRRRRROOOOORRRRRRRRRRRRRDDDDDDDDDDDDDOOOO",
                    "PPRRRRJJJEEEEEEMMSSSHHHHHHMMMMMMMMMMMHHHHGGGGGGGGTTTTTOTTTWWWWWWWWWWWWIGULLLLLULLLIIIIOOOOVVVVVVVVRRRRRRZOOOOOORRRRRRRRRRRRDDDDDDDDDDDDDDDOO",
                    "PPJJJJJJEEEEEESSMSSSHHHHHHHHMMMMMMMMMHHHHCGGGGGGGTTTTTTOWWWWWWWWWWWWWWKKULLLLLULLLIIOOOOVVVVVVVRRRROOROROOOOOOORRRRRRRRRRERDDDDDDDDDDDDDSOOO",
                    "PPJJJJJJEEEEEESSSSSSSHHHHHHHMMMMMMMMMNHHBNGGGGGGGTTTTTTTWWWWWWWWWWWWWWKKUULLUUULILIIIIIOVVVDVRRRRROOOOOOOOOOOOORRRRRRRRBJJJJJJDDDDDDDDDSSOOO",
                    "PJJJJJJJEEEEESSSSSSSSHHHHHMMMMMMMMMMMNHHBNGGGGGGGGOOOTTTWWWWWWWWWWWWWWKKUULRRRRRRRRIIIIIDDDDRRRRROOOCOOOOOOOOOORRRRRRNRRJJJJJJDDDDDDDDOSSSSS",
                    "JJJJJJJJEEEEESSSSSSSSSSSHHMMMMMMMMMMMNNNNNYGGGGGGGOOOTTTWWWWWWSSSGSLLKKKUUURRRRRRRRIIIIDDDDDDRRRROOOOOOOOOOOOOORRROHONNJJJRJDDDDDDDKDOOOSSSS",
                    "JJJJJJJEEEEEEECCCCSCSHHHHMMMMMMMMMMMMNNNNNGGGGGGGGTOTTTTWWWWWWSSSSSLLKKKKUKRRRRRRRRIIIIIDDDDDDRRDOOODOOOOOOOOOOOOOOOONNNRRRRDDDDDRRRDOSSSSSS",
                    "JJJJJJJEEEEEECCCCCCCCHHHHMMMMMMMOHNNNNNNNNHGGGGGGGTTTTTTTTTOSSSSSSLLLLKKKKKRRRRRRRRIIIIIDDDDDDRRDDDDDDAAOOOOOOOOOOOOOONNRRRRRDKRDRRRROOSSSSS",
                    "BBBEEEEEEEEEECCCCCCCCCHHHMMMMMMMOONNNNNNHHHHGGGGGGGTTTTTTTTTTSSSSSLLLLKKKKKRRRRRRRRIIIIDDDDDDDDDDDDDDDAAOOOOOOOOOOOOOONNRRRRRRRRRRRRGOOOSSSS",
                    "BBBEEEEEEEECECCCCCCTTTHHHMMMMMMMOOOOKNHHHHHGGGGGGGTTTTTTTTTTLLSSLLLLLLLLLKKRRRRRRRRIIIIIILLLDDDDDDDDDDDAOOOOOOOOOOONNNNNRRRRRRRRRRRRGOGSSSSS",
                    "BBEEEEEEEECCCNCCCCCTTTTHHMMMMMMOOOOOOHHHHHHEEGGTTTTTTTTTTPPFPLLSLLLLLLLLLKKRRRRRRRRIIIIIILLDDDDDDDDDDDDAOVOOOTOOOOONNNJRRRRRRRRRRRRRGGGGSSSS",
                    "BEEEEEEZZCKCCCCCCCCTTTTHHMMMMMMOOOOOOOHHHHEEEETTTTPPTTTTTPPPPPLLLLLLLLLLLKKRRRRRRRRIIIIIILLLDDDDDDDDDDDDYVOYTTTOMMMMJJJJJRRRRRRRRRRRGGGGGSSS",
                    "BBBEEEEEZCCCCCCCCCCCCTTTTMMMMMMOOOOOOOOHHELEEEETTPPPTTPPTPPPPPLLLLLLLLLEEKKKKKKIIIIIWWIIIILLLDDDDDDDDDDDYYYYYTYYYMMMJJJJJJRRRRRRRRRRGGGGGSGH",
                    "BBBBEEEEEELCCCCMCCCCCIIIIMMMMMMOOOOOOOHHHEEEEEETTTPPPTPPPPPPPLLLLLLLLLEEEKKKKKUIIIEEEWEIIILLLDDDDDDDDDDDYYYYYYYYYMMJJJJJJRRRRRRRRRLRGGGGGGGH",
                    "BBBQMMEKKKMTTCMMCICICIIIIIIIOOOOOOOOOOOHHEGEEEETTPPPPPPPPPPPPLLPPLBLLEEEEKKKKUUUUEEWWWEEIILLLLDDDDDDDDDDYYYYYYYYYMMMJJJJJRRRRRRRRRLLLGNGGGGG",
                    "BBQQQMQKQQMMMCCMMIIIIIIIIIIOOOOOOOOOOOOHHGGGGEETTTGPPPPPPPPPPPPPPPPEEEEEKKKKKUUEEEEWWEEEELLLLDDDDDDDDDYYYYYYYYYYMMMJJJJJJRRRRRRRRRRLGGNGGGGG",
                    "BBQQQQQQQQMMMMMMMIIIIIIIIIIOOOOOOOOOOOOOHGGGGEEGGTGGPPPPPPPPPPPPPPPEEEEEEKKKLEEEEEEEEEEEELLLLLDDDDDDDTYYYYYYYMMMMMMJJJJJJRRRRRRRPPRLGGGGGGGG",
                    "BBQQQQQQQQQMMMMMMMIIIIIIIIIOOOOOOJJOUOUUGGGGGGGGGGGGGPPPPPPPPPPPPPPPEEEEEEEKLLEEEEEEEEEEEELLLLLDDDDDTTYYYYYYYMMMJJJJJJJJJJJRREEPPPPGGGGGGGGG",
                    "QQQQQQQQQQQQLMMMMMMIIIIIIJIOOOOOOJDUUUUUGGGGGGGGGGGGGPPPPPPPPPPPPPPPEEEEEEEELLLEEEEEEEEEEZZLLLLDDLDTTTTYYYYYYMMMMJVJJJJJJRJEEEEEPPPPGGGGGGGG",
                    "DQQQQQQQQQQMMMUUUMMIIIIIIIIDOOOODDDUUUUUUGGGGGGGGGGGGGGGGPPPPPPFPPPPEEEEEEELLLLEEEEEEEEEEZZZLLLLLLLLYYYYYYMMMMMMMVVVVJJJJJJTEPPPPPPPGGGGGGGG",
                    "DQQQQQQQQQQUUUUUIIMIIIIIDDDDDOODDDDUUUUUUGGGGGGGGGGGGGGGGGPPPPPPLPPXEEEEEEELLLLEEEEEEEEEEZZZLLLLLLLLLQQYMMMMMMMMMVVVJJJJTTTTEEPMPPPPGGGGGOGG",
                    "QQQQQQQQQQQUUUQUIIIIIIIIDDDDDODDDDUUUUUUGGGGGGGGGGGGGGGWGPPPPPPPLPPEEEEEEELLLEEEEEEEEEEEEEZZZLLLLLLLLLQQMMMMMMMMMVVTCJJLTTTTEEMMMPPPPPGGGOOU",
                    "QQQQQQQQQQQQQQQINIIIIIIDDDDDDDDDDDDUUUUUGGGGGGGGGGGGGGGGGPPPPPPLLLLLEEEELLLLEEEEEEEEEEEEWZZZZLLLLLLLLLMMMMMMMMMMMVVTTTTTTTTTTMMMMPPPPPPPOOUU",
                    "QQQQQQQQQQQQQIIIIIIIIIIDDDDDDDDDDDDDUUGGGGGGGGGGGGGGGGGGJJPPPPPPPLLLLLLLLLLLLEEEEEEEEEEEZZZZZLLLLLLLLPPPMMMMMMMMMVVVVTTTTTTTTCMMPPPPPPOPOOUU",
                    "QQQQQQQQQQQQRRIIIIISIIIDDDDDDDDDDDDDDDDRGGGGGGGGGGGGGGGJJJJJPJPPLLLLLLLLLLLLLLEEEEEEEEEEZEZZZLLLLLPPPPPMMMMMMMMMMMMMVVTTTTTTTMMMMMMOOOOOOOUU",
                ).map { it },
                debug = true
            ).part2()
        )
    }
}
